name: Build and deploy

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: './wiki'


jobs:
  build_wiki:
    runs-on: ubuntu-latest
    name: "Build the Wiki"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './wiki/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Build site
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wiki
        path: wiki/dist/
        retention-days: 7

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
        key: wiki-${{ runner.os }}-node-${{ hashFiles('wiki/**/package-lock.json') }}
        restore-keys: |
          wiki-${{ runner.os }}-node-

  build_edge_lambda:
    runs-on: ubuntu-latest
    name: "Build the Lambda@Edge code"
    defaults:
      run:
        working-directory: ./deployment/aws/lambda-edge/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './deployment/aws/lambda-edge/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-edge
          path: ./deployment/aws/lambda-edge/src/**/bundle.js
          retention-days: 7

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: lambda-edge-${{ runner.os }}-node-${{ hashFiles('deployment/aws/lambda-edge/**/package-lock.json') }}
          restore-keys: |
            lambda-edge-${{ runner.os }}-node-

  plan_tofu:
    runs-on: ubuntu-latest
    name: "Plan the OpenTofu infrastructure upgrade"
    defaults:
      run:
        working-directory: ./deployment/aws/infrastructure/
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Plan
        id: plan
        run: tofu plan -no-color -out=tfplan

      - name: Upload Tofu plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./deployment/aws/infrastructure/tfplan
          retention-days: 7

  deploy_aws:
    runs-on: ubuntu-latest
    name: "Deploy the infrastructure and artifacts to AWS"
    needs: [build_wiki, build_edge_lambda, plan_tofu]
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./repo

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: true

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Install boto3
        run: pip install boto3

      - name: OpenTofu Init
        run: tofu init

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids: wiki, lambda-edge, tfplan

      - name: Apply Tofu plan
        id: tofu_apply
        run: |
          tofu apply tfplan

      - name: Deploy Lambda@Edge and Wiki
        run: |
          echo "${{ steps.tofu_apply.outputs }}"
          python3 ./repo/deployment/aws/deploy.py  # TODO Add all variables required to deploy
