# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Check Wiki on PR
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'wiki/**'
      - '.github/workflows/check-wiki.yml'

jobs:
  build_wiki:
    runs-on: ubuntu-latest
    name: "Build the Wiki"
    defaults:
      run:
        working-directory: ./wiki

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: './wiki/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Prettier check
      run: npx prettier . --check

    - name: Build site
      run: npm run build
