# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Generate new and changed policies

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'policies/**'
      - '.github/workflows/generate-changed-policies.yml'

jobs:
  update_policies:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.repository == github.repository
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Warn about GEMINI_API_KEY secret
      uses: actions/github-script@v7
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      if: ${{ env.GEMINI_API_KEY == ''}}
      with:
        script: |
          const message = `### ⚠️  You haven't configured a Gemini API key.

          You should add an API key as a repository **secret**:
          [Using secrets in GitHub Actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions)
          `
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message,
          })

          throw new Error("You haven't configured a Gemini API key.")
    - name: Update policies
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        updated_policies=$(python3 deployment/update_policies.py --base-ref "origin/${{ github.base_ref }}")
        if [ -z "${updated_policies}" ]; then
          echo "No policies updated."
        else
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$(cat <<EOF
          Generated markdown files

          $updated_policies
        EOF
          )"
          git push
        fi
